name: build and deploy to pages
run-name: deploy ${{ github.ref }}
on:
  repository_dispatch:
    types: [deploy]
  push:
    branches: [trunk]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v6
      - name: mise install
        uses: jdx/mise-action@v4
      - name: checkout wiki
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.WIKI_REPO }}
          token: ${{ secrets.WIKI_SRC_PAT }}
          path: ./bdlmwiki
      - name: analyze wiki & build site
        run: mise run build
        env:
          WIKI_PATH: ./bdlmwiki
      - name: configure pages
        uses: actions/configure-pages@v5
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v5
